//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DzMobilki
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS
    {
        public int Id { get; set; }
        public int IdPhone { get; set; }
        public int IdCustomer { get; set; }
    
        public virtual CUSTOMERS CUSTOMERS { get; set; }
        public virtual PHONES PHONES { get; set; }
    }
}
