CREATE TABLE PHONES(
Id INT PRIMARY KEY IDENTITY,
Name NVARCHAR(100) NOT NULL,
Model NVARCHAR(100) NOT NULL,
Price MONEY NOT NULL
)

CREATE TABLE CUSTOMERS(
Id INT PRIMARY KEY IDENTITY,
Name NVARCHAR(100) NOT NULL,
)

CREATE TABLE ORDERS(
Id INT PRIMARY KEY IDENTITY,
IdPhone INT NOT NULL,
IdCustomer INT NOT NULL
)

GO

ALTER TABLE ORDERS
ADD CONSTRAINT LOLOLOLO
FOREIGN KEY (IdPhone) REFERENCES PHONES(Id),
CONSTRAINT LOLOLOLO1
FOREIGN KEY (IdCustomer) REFERENCES CUSTOMERS(Id)

