//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityPractica1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEBTORS
    {
        public int Id { get; set; }
        public int IdGuest { get; set; }
        public int IdBook { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual BOOKS BOOKS { get; set; }
        public virtual GUEST GUEST { get; set; }
    }
}
